import { exp } from "react-native-reanimated";

// АВТОРИЗАЦИЯ
export const USER_FOUND = 'USER_FOUND';
export const GET_ERRORS = 'GET_ERRORS';
export const SET_NOT_LOGGED_IN = 'SET_NOT_LOGGED_IN';
export const SET_USER_LOGGED = 'SET_USER_LOGGED';
export const SET_LOGGING_IN = 'SET_LOGGING_IN';
export const SET_USER_LOGGED_SAVED = 'SET_USER_LOGGED_SAVED';
export const SET_LOGOUT = 'SET_LOGOUT';

//TODO
export const TODOS_FOUND = 'TODOS_FOUND';
export const TODOS_LOADING = 'TODOS_LOADING';
export const TODO_COMPLETED = 'TODO_COMPLETED';

//BRIGADES
export const BRIGADE_LOADING = 'BRIGADE_LOADING';
export const BRIGADE_LOADED = 'BRIGADE_LOADED';
export const BRIGADE_SELECTED = 'BRIGADE_SELECTED';
//BRIGADES CAR
export const BRIGADE_CAR_LOADING = 'BRIGADE_CAR_LOADING';
export const BRIGADE_CAR_LOADED = 'BRIGADE_CAR_LOADED';
export const BRIGADE_CAR_SELECTED = 'BRIGADE_CAR_SELECTED';
//SET BRIGADE
export const BRIGADE_SETING = 'BRIGADE_SETING';
export const BRIGADE_SETED = 'BRIGADE_SETED';
//BRIGADE USER LIST
export const BRIGADE_USER_LOADED = 'BRIGADE_USER_LOADED';
export const BRIGADE_USER_LOADING = 'BRIGADE_USER_LOADING';
export const BRIGADE_USERS_ADDING = 'BRIGADE_USERS_ADDING';
export const BRIGADE_USERS_ADDED = 'BRIGADE_USERS_ADDED';

export const BRIGADE_EQUIP_LOADED = 'BRIGADE_EQUIP_LOADED';
export const BRIGADE_EQUIP_LOADING = 'BRIGADE_EQUIP_LOADING';

export const BRIGADE_EQUIP_CHANGE = 'BRIGADE_EQUIP_CHANGE';
export const BRIGADE_EQUIP_UPDATE = 'BRIGADE_EQUIP_UPDATE';
export const CAR_EQUIP_UPDATE = 'CAR_EQUIP_UPDATE';

export const UPDATE_COPY_ROW = 'UPDATE_COPY_ROW';
export const UPDATE_COPY_ROW_OXY = 'UPDATE_COPY_ROW_OXY';

export const REPORT_SENDING = 'REPORT_SENDING';
export const REPORT_SENDED = 'REPORT_SENDED';

export const FOUND_YOUR_BRIGADE = 'FOUND_YOUR_BRIGADE';
export const FINDING_YOUR_BRIGADE = 'FINDING_YOUR_BRIGADE';

export const PASS_YOUR_BRIGADE = 'PASS_YOUR_BRIGADE';
export const PASSING_YOUR_BRIGADE = 'PASSING_YOUR_BRIGADE';

export const RESET_BRIGADE = 'RESET_BRIGADE';

export const SAVE_RECIPE = 'SAVE_RECIPE';
export const RECIPE_SENDED = 'RECIPE_SENDED';
export const RECIPE_SENDING = 'RECIPE_SENDING';
export const FOUND_YOUR_BRIGADE_RECIPE = 'FOUND_YOUR_BRIGADE_RECIPE';

export const EQUIP_INFO_LOADING = 'EQUIP_INFO_LOADING';
export const EQUIP_INFO_LOADED = 'EQUIP_INFO_LOADED';