export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//CPUsers
export const GET_USERS_LIST = "GET_USERS_LIST";
export const LOADING_USERS = "LOADING_USERS";
export const GET_USERS_ERRORS = "GET_USERS_ERRORS";
export const USER_ADDED = "USER_ADDED";
export const USER_DELETED = "USER_DELETED";
export const USER_EDITED = "USER_EDITED";

//CPTodos
export const USER_TODO_LOADED = "USER_TODO_LOADED";
export const USER_TODO_LOADING = "USER_TODO_LOADING";
export const USER_TODO_DELETED = "USER_TODO_DELETED";
export const USER_TODO_DELETING = "USER_TODO_DELETING";
export const USER_TODO_ADDING = "USER_TODO_ADDING";
export const USER_TODO_ADDED = "USER_TODO_ADDED";
export const USER_MASS_TODO_ADDED = "USER_MASS_TODO_ADDED";

//CPDashboard
export const DASHBOARD_LOADED = "DASHBOARD_LOADED";
export const DASHBOARD_LOADING = "DASHBOARD_LOADING";
export const DASHBOARD_ERRORS = "DASHBOARD_ERRORS";
export const DASHBOARD_DEADLINED_TODOS_LOADED = "DASHBOARD_DEADLINED_TODOS_LOADED";
export const DASHBOARD_DEADLINED_TODOS_LOADING = "DASHBOARD_DEADLINED_TODOS_LOADING";
export const DASHBOARD_DEADLINED_TODOS_CLEAR = "DASHBOARD_DEADLINED_TODOS_CLEAR";
export const DASHBOARD_ONGOING_TODOS_LOADED = "DASHBOARD_ONGOING_TODOS_LOADED";
export const DASHBOARD_ONGOING_TODOS_LOADING = "DASHBOARD_ONGOING_TODOS_LOADING";
export const DASHBOARD_ONGOING_TODOS_CLEAR = "DASHBOARD_ONGOING_TODOS_CLEAR";
export const DASHBOARD_COMPLETED_TODOS_LOADED = "DASHBOARD_COMPLETED_TODOS_LOADED";
export const DASHBOARD_COMPLETED_TODOS_LOADING = "DASHBOARD_COMPLETED_TODOS_LOADING";
export const DASHBOARD_COMPLETED_TODOS_CLEAR = "DASHBOARD_COMPLETED_TODOS_CLEAR";
export const USER_DEADLINED_TODO_DELETED = "USER_DEADLINED_TODO_DELETED";
export const USER_DEADLINED_TODOS_DELETED = "USER_DEADLINED_TODOS_DELETED";

//CPBrigades
export const BRIGADE_INFO_LOADED = "BRIGADE_INFO_LOADED";
export const BRIGADE_INFO_LOADING = "BRIGADE_INFO_LOADING";
export const BRIGADE_ERRORS = "BRIGADE_ERRORS";
export const BRIGADE_ADDED = "BRIGADE_ADDED";
export const BRIGADE_CAR_ADDED = "BRIGADE_CAR_ADDED";
export const BRIGADE_REPORTS_LOADED = "BRIGADE_REPORTS_LOADED";
export const BRIGADE_REPORTS_LOADING = "BRIGADE_REPORTS_LOADING";
export const SET_NEED_TO_UPDATE_REPORT_BY_ID = "SET_NEED_TO_UPDATE_REPORT_BY_ID";
export const CLEAR_NEED_TO_UPDATE_REPORT_BY_ID = "CLEAR_NEED_TO_UPDATE_REPORT_BY_ID";
export const CLEAR_ANIMATION = "CLEAR_ANIMATION";
export const REPORT_BY_ID_LOADED = "REPORT_BY_ID_LOADED";
export const NEED_TO_DELETE_REPORT_BY_ID = "NEED_TO_DELETE_REPORT_BY_ID";

export const BRIGADE_REPORT_KV_SEARCHING = "BRIGADE_REPORT_KV_SEARCHING";
export const BRIGADE_REPORT_KV_FOUND = "BRIGADE_REPORT_KV_FOUND";

export const EQUIPMENT_LOADING = "EQUIPMENT_LOADING";
export const EQUIPMENT_LOADED = "EQUIPMENT_LOADED";
export const EQUIPMENT_DELETED = "EQUIPMENT_DELETED";
export const EQUIPMENT_DELETING = "EQUIPMENT_DELETING";
export const EQUIPMENT_ADDED = "EQUIPMENT_ADDED";
export const EQUIPMENT_ADDING = "EQUIPMENT_ADDING";
export const EQUIPMENT_EDITING = "EQUIPMENT_EDITING";
export const EQUIPMENT_EDITED = "EQUIPMENT_EDITED";  
export const EQUIPMENT_ERROR = "EQUIPMENT_ERROR";